name: trigger jenkins job
on: [workflow_dispatch]
jobs:
  build:
    name: Trigger my first job
    runs-on: ubuntu-latest
    steps:
    - name: trigger single Job
      uses: appleboy/jenkins-action@master
      with:
        url: "https://ci.saccada.xyz"
        user: ${{ secrets.USER }}
        token: ${{ secrets.TOKEN }}
        job: "My_first_job"

